import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "pt" | "en" | "es" | "ru";

export const LANGUAGES = [
  { code: "pt" as Lang, label: "PT", flag: "🇧🇷", name: "Português" },
  { code: "en" as Lang, label: "EN", flag: "🇺🇸", name: "English" },
  { code: "es" as Lang, label: "ES", flag: "🇪🇸", name: "Español" },
  { code: "ru" as Lang, label: "RU", flag: "🇷🇺", name: "Русский" },
];

export const translations = {
  pt: {
    nav: {
      hosting: "Hospedagem",
      vps: "VPS",
      domains: "Domínios",
      security: "Segurança",
      payments: "Pagamentos",
      start: "Começar Agora",
      online: "ONLINE",
    },
    hero: {
      badge: "Certificado Google Cybersecurity",
      title1: "Hospedagem",
      title2: "de Elite",
      title3: "para Devs",
      subtitle: "Infraestrutura dedicada com segurança de nível Google. Aceite pagamentos em",
      subtitleHighlight: "Bitcoin, Ethereum, Stripe e Pix",
      subtitleEnd: ". Suporte 24/7 via IA.",
      cta1: "Ver Planos",
      cta2: "Nossa Segurança",
      stat1: "Uptime",
      stat2: "SSL Grátis",
      stat3: "CDN Global",
      stat4: "Suporte IA",
    },
    plans: {
      badge: "Planos & Preços",
      title1: "Escolha seu",
      title2: "Plano",
      subtitle: "Infraestrutura de alta performance com preços acessíveis. Aceite pagamentos em qualquer moeda.",
      hosting: "Hospedagem",
      vps: "VPS",
      monthly: "Mensal",
      annual: "Anual",
      save: "Economize 30%",
      popular: "MAIS POPULAR",
      perMonth: "/mês",
      annualNote: "cobrado anualmente",
      hire: "Contratar",
      comingSoon: "Em Breve",
      domainsNote: "Registro de domínios a partir de",
      domainsNote2: "Extensões: .com.br, .com, .net, .org, .io, .dev e mais.",
    },
    security: {
      badge: "Segurança de Elite",
      title1: "Protegido por quem",
      title2: "entende",
      subtitle: "Nossa infraestrutura é gerenciada por um especialista certificado pela Google em Cybersecurity.",
      certTitle: "Google Cybersecurity",
      certSub: "Certificado Profissional",
      certDesc: "Fundador certificado pela Google em Cybersecurity — 8 cursos completos incluindo Python, Linux, SQL, SIEM e Detecção de Intrusão.",
      feat1: "Proteção contra ataques de negação de serviço em todas as camadas de rede.",
      feat2: "Certificados SSL automáticos via Let's Encrypt em todos os planos.",
      feat3title: "Monitoramento 24/7",
      feat3: "Sistemas de detecção de intrusão (IDS) ativos continuamente.",
      feat4: "WAF com regras atualizadas em tempo real.",
      feat5title: "Backup Automático",
      feat5: "Snapshots diários com retenção de 30 dias e restauração em 1 clique.",
      feat6title: "Detecção de Malware",
      feat6: "Varredura automática e isolamento de ameaças antes que causem danos.",
    },
    payments: {
      badge: "Pagamentos Globais",
      title1: "Pague como",
      title2: "quiser",
      subtitle: "Aceitamos as principais criptomoedas, cartões internacionais e Pix. Você escolhe a moeda, nós cuidamos do resto.",
      currencies: "Moedas Aceitas",
      imageCaption: "Aceite pagamentos de qualquer lugar do mundo",
      ben1title: "Aceite de qualquer país",
      ben1: "Receba em USD, EUR, BRL e criptomoedas sem fronteiras.",
      ben2title: "Confirmação instantânea",
      ben2: "Pagamentos via Pix são confirmados em segundos.",
      ben3title: "100% Seguro",
      ben3: "Todos os gateways são criptografados e auditados.",
      ben4title: "Taxas competitivas",
      ben4: "Menores taxas do mercado para transações internacionais.",
    },
    domains: {
      badge: "Domínios",
      title1: "Seu domínio",
      title2: "perfeito",
      subtitle: "Registre, transfira ou renove seu domínio com facilidade. Suporte a dezenas de extensões.",
      search: "Buscar domínio...",
      searchBtn: "Buscar",
      from: "a partir de",
      perYear: "/ano",
      available: "Disponível",
      comingSoon: "Em breve",
      popular: "Popular",
    },
    footer: {
      tagline: "Hospedagem de elite com segurança certificada pela Google. Infraestrutura dedicada para desenvolvedores e empresas.",
      rights: "Todos os direitos reservados.",
      hosting: "Hospedagem",
      company: "Empresa",
      support: "Suporte",
      about: "Sobre nós",
      blog: "Blog",
      careers: "Carreiras",
      contact: "Contato",
      docs: "Documentação",
      status: "Status",
      privacy: "Privacidade",
      terms: "Termos",
    },
    chat: {
      placeholder: "Pergunte algo...",
      poweredBy: "Powered by LLaMA 3 · DevHosting IA",
      online: "Online agora",
      suggestions: [
        "Qual plano é ideal para meu site?",
        "Vocês aceitam Bitcoin?",
        "Como funciona o VPS?",
        "Preço do domínio .com.br?",
      ],
    },
  },
  en: {
    nav: {
      hosting: "Hosting",
      vps: "VPS",
      domains: "Domains",
      security: "Security",
      payments: "Payments",
      start: "Get Started",
      online: "ONLINE",
    },
    hero: {
      badge: "Google Cybersecurity Certified",
      title1: "Elite",
      title2: "Hosting",
      title3: "for Devs",
      subtitle: "Dedicated infrastructure with Google-level security. Accept payments in",
      subtitleHighlight: "Bitcoin, Ethereum, Stripe and Pix",
      subtitleEnd: ". 24/7 AI support.",
      cta1: "View Plans",
      cta2: "Our Security",
      stat1: "Uptime",
      stat2: "Free SSL",
      stat3: "Global CDN",
      stat4: "AI Support",
    },
    plans: {
      badge: "Plans & Pricing",
      title1: "Choose your",
      title2: "Plan",
      subtitle: "High-performance infrastructure at affordable prices. Accept payments in any currency.",
      hosting: "Hosting",
      vps: "VPS",
      monthly: "Monthly",
      annual: "Annual",
      save: "Save 30%",
      popular: "MOST POPULAR",
      perMonth: "/mo",
      annualNote: "billed annually",
      hire: "Get Started",
      comingSoon: "Coming Soon",
      domainsNote: "Domain registration from",
      domainsNote2: "Extensions: .com, .net, .org, .io, .dev and more.",
    },
    security: {
      badge: "Elite Security",
      title1: "Protected by someone who",
      title2: "knows",
      subtitle: "Our infrastructure is managed by a Google-certified Cybersecurity specialist.",
      certTitle: "Google Cybersecurity",
      certSub: "Professional Certificate",
      certDesc: "Founder certified by Google in Cybersecurity — 8 complete courses including Python, Linux, SQL, SIEM and Intrusion Detection.",
      feat1: "Protection against denial-of-service attacks across all network layers.",
      feat2: "Automatic SSL certificates via Let's Encrypt on all plans.",
      feat3title: "24/7 Monitoring",
      feat3: "Intrusion detection systems (IDS) running continuously.",
      feat4: "WAF with rules updated in real time.",
      feat5title: "Automatic Backup",
      feat5: "Daily snapshots with 30-day retention and 1-click restore.",
      feat6title: "Malware Detection",
      feat6: "Automatic scanning and threat isolation before damage occurs.",
    },
    payments: {
      badge: "Global Payments",
      title1: "Pay however",
      title2: "you want",
      subtitle: "We accept major cryptocurrencies, international cards and Pix. You choose the currency, we handle the rest.",
      currencies: "Accepted Currencies",
      imageCaption: "Accept payments from anywhere in the world",
      ben1title: "Accept from any country",
      ben1: "Receive in USD, EUR, BRL and crypto without borders.",
      ben2title: "Instant confirmation",
      ben2: "Pix payments are confirmed in seconds.",
      ben3title: "100% Secure",
      ben3: "All gateways are encrypted and audited.",
      ben4title: "Competitive fees",
      ben4: "Lowest market fees for international transactions.",
    },
    domains: {
      badge: "Domains",
      title1: "Your perfect",
      title2: "domain",
      subtitle: "Register, transfer or renew your domain with ease. Support for dozens of extensions.",
      search: "Search domain...",
      searchBtn: "Search",
      from: "from",
      perYear: "/year",
      available: "Available",
      comingSoon: "Coming soon",
      popular: "Popular",
    },
    footer: {
      tagline: "Elite hosting with Google-certified security. Dedicated infrastructure for developers and businesses.",
      rights: "All rights reserved.",
      hosting: "Hosting",
      company: "Company",
      support: "Support",
      about: "About us",
      blog: "Blog",
      careers: "Careers",
      contact: "Contact",
      docs: "Documentation",
      status: "Status",
      privacy: "Privacy",
      terms: "Terms",
    },
    chat: {
      placeholder: "Ask something...",
      poweredBy: "Powered by LLaMA 3 · DevHosting AI",
      online: "Online now",
      suggestions: [
        "Which plan is best for my site?",
        "Do you accept Bitcoin?",
        "How does VPS work?",
        "Domain .com price?",
      ],
    },
  },
  es: {
    nav: {
      hosting: "Alojamiento",
      vps: "VPS",
      domains: "Dominios",
      security: "Seguridad",
      payments: "Pagos",
      start: "Comenzar Ahora",
      online: "EN LÍNEA",
    },
    hero: {
      badge: "Certificado Google Cybersecurity",
      title1: "Alojamiento",
      title2: "de Élite",
      title3: "para Devs",
      subtitle: "Infraestructura dedicada con seguridad de nivel Google. Acepta pagos en",
      subtitleHighlight: "Bitcoin, Ethereum, Stripe y Pix",
      subtitleEnd: ". Soporte 24/7 vía IA.",
      cta1: "Ver Planes",
      cta2: "Nuestra Seguridad",
      stat1: "Uptime",
      stat2: "SSL Gratis",
      stat3: "CDN Global",
      stat4: "Soporte IA",
    },
    plans: {
      badge: "Planes & Precios",
      title1: "Elige tu",
      title2: "Plan",
      subtitle: "Infraestructura de alto rendimiento a precios accesibles. Acepta pagos en cualquier moneda.",
      hosting: "Alojamiento",
      vps: "VPS",
      monthly: "Mensual",
      annual: "Anual",
      save: "Ahorra 30%",
      popular: "MÁS POPULAR",
      perMonth: "/mes",
      annualNote: "facturado anualmente",
      hire: "Contratar",
      comingSoon: "Próximamente",
      domainsNote: "Registro de dominios desde",
      domainsNote2: "Extensiones: .com, .net, .org, .io, .dev y más.",
    },
    security: {
      badge: "Seguridad de Élite",
      title1: "Protegido por quien",
      title2: "entiende",
      subtitle: "Nuestra infraestructura es administrada por un especialista certificado por Google en Ciberseguridad.",
      certTitle: "Google Cybersecurity",
      certSub: "Certificado Profesional",
      certDesc: "Fundador certificado por Google en Ciberseguridad — 8 cursos completos incluyendo Python, Linux, SQL, SIEM y Detección de Intrusiones.",
      feat1: "Protección contra ataques de denegación de servicio en todas las capas de red.",
      feat2: "Certificados SSL automáticos vía Let's Encrypt en todos los planes.",
      feat3title: "Monitoreo 24/7",
      feat3: "Sistemas de detección de intrusiones (IDS) activos continuamente.",
      feat4: "WAF con reglas actualizadas en tiempo real.",
      feat5title: "Copia de seguridad automática",
      feat5: "Snapshots diarios con retención de 30 días y restauración en 1 clic.",
      feat6title: "Detección de Malware",
      feat6: "Escaneo automático y aislamiento de amenazas antes de que causen daño.",
    },
    payments: {
      badge: "Pagos Globales",
      title1: "Paga como",
      title2: "quieras",
      subtitle: "Aceptamos las principales criptomonedas, tarjetas internacionales y Pix. Tú eliges la moneda, nosotros nos encargamos del resto.",
      currencies: "Monedas Aceptadas",
      imageCaption: "Acepta pagos desde cualquier lugar del mundo",
      ben1title: "Acepta de cualquier país",
      ben1: "Recibe en USD, EUR, BRL y criptomonedas sin fronteras.",
      ben2title: "Confirmación instantánea",
      ben2: "Los pagos vía Pix se confirman en segundos.",
      ben3title: "100% Seguro",
      ben3: "Todos los gateways están cifrados y auditados.",
      ben4title: "Tarifas competitivas",
      ben4: "Las tarifas más bajas del mercado para transacciones internacionales.",
    },
    domains: {
      badge: "Dominios",
      title1: "Tu dominio",
      title2: "perfecto",
      subtitle: "Registra, transfiere o renueva tu dominio fácilmente. Soporte para docenas de extensiones.",
      search: "Buscar dominio...",
      searchBtn: "Buscar",
      from: "desde",
      perYear: "/año",
      available: "Disponible",
      comingSoon: "Próximamente",
      popular: "Popular",
    },
    footer: {
      tagline: "Alojamiento de élite con seguridad certificada por Google. Infraestructura dedicada para desarrolladores y empresas.",
      rights: "Todos los derechos reservados.",
      hosting: "Alojamiento",
      company: "Empresa",
      support: "Soporte",
      about: "Sobre nosotros",
      blog: "Blog",
      careers: "Carreras",
      contact: "Contacto",
      docs: "Documentación",
      status: "Estado",
      privacy: "Privacidad",
      terms: "Términos",
    },
    chat: {
      placeholder: "Pregunta algo...",
      poweredBy: "Powered by LLaMA 3 · DevHosting IA",
      online: "En línea ahora",
      suggestions: [
        "¿Qué plan es ideal para mi sitio?",
        "¿Aceptan Bitcoin?",
        "¿Cómo funciona el VPS?",
        "¿Precio del dominio .com?",
      ],
    },
  },
  ru: {
    nav: {
      hosting: "Хостинг",
      vps: "VPS",
      domains: "Домены",
      security: "Безопасность",
      payments: "Платежи",
      start: "Начать сейчас",
      online: "ОНЛАЙН",
    },
    hero: {
      badge: "Сертификат Google Cybersecurity",
      title1: "Элитный",
      title2: "Хостинг",
      title3: "для Разработчиков",
      subtitle: "Выделенная инфраструктура с безопасностью уровня Google. Принимайте платежи в",
      subtitleHighlight: "Bitcoin, Ethereum, Stripe и Pix",
      subtitleEnd: ". Поддержка 24/7 через ИИ.",
      cta1: "Посмотреть планы",
      cta2: "Наша безопасность",
      stat1: "Аптайм",
      stat2: "SSL бесплатно",
      stat3: "Глобальный CDN",
      stat4: "ИИ поддержка",
    },
    plans: {
      badge: "Планы и цены",
      title1: "Выберите свой",
      title2: "план",
      subtitle: "Высокопроизводительная инфраструктура по доступным ценам. Принимайте платежи в любой валюте.",
      hosting: "Хостинг",
      vps: "VPS",
      monthly: "Ежемесячно",
      annual: "Ежегодно",
      save: "Экономия 30%",
      popular: "ПОПУЛЯРНЫЙ",
      perMonth: "/мес",
      annualNote: "оплата ежегодно",
      hire: "Подключить",
      comingSoon: "Скоро",
      domainsNote: "Регистрация доменов от",
      domainsNote2: "Расширения: .com, .net, .org, .io, .dev и другие.",
    },
    security: {
      badge: "Элитная безопасность",
      title1: "Защищено тем, кто",
      title2: "понимает",
      subtitle: "Наша инфраструктура управляется специалистом, сертифицированным Google по кибербезопасности.",
      certTitle: "Google Cybersecurity",
      certSub: "Профессиональный сертификат",
      certDesc: "Основатель сертифицирован Google по кибербезопасности — 8 полных курсов, включая Python, Linux, SQL, SIEM и обнаружение вторжений.",
      feat1: "Защита от DDoS-атак на всех уровнях сети.",
      feat2: "Автоматические SSL-сертификаты через Let's Encrypt на всех планах.",
      feat3title: "Мониторинг 24/7",
      feat3: "Системы обнаружения вторжений (IDS) работают непрерывно.",
      feat4: "WAF с правилами, обновляемыми в реальном времени.",
      feat5title: "Автоматическое резервное копирование",
      feat5: "Ежедневные снимки с хранением 30 дней и восстановлением в 1 клик.",
      feat6title: "Обнаружение вредоносного ПО",
      feat6: "Автоматическое сканирование и изоляция угроз до нанесения ущерба.",
    },
    payments: {
      badge: "Глобальные платежи",
      title1: "Платите как",
      title2: "хотите",
      subtitle: "Принимаем основные криптовалюты, международные карты и Pix. Вы выбираете валюту, мы берём остальное на себя.",
      currencies: "Принимаемые валюты",
      imageCaption: "Принимайте платежи из любой точки мира",
      ben1title: "Принимайте из любой страны",
      ben1: "Получайте в USD, EUR, BRL и криптовалютах без границ.",
      ben2title: "Мгновенное подтверждение",
      ben2: "Платежи через Pix подтверждаются за секунды.",
      ben3title: "100% Безопасно",
      ben3: "Все шлюзы зашифрованы и проверены.",
      ben4title: "Конкурентные комиссии",
      ben4: "Низкие комиссии для международных транзакций.",
    },
    domains: {
      badge: "Домены",
      title1: "Ваш идеальный",
      title2: "домен",
      subtitle: "Регистрируйте, переносите или продлевайте домен легко. Поддержка десятков расширений.",
      search: "Поиск домена...",
      searchBtn: "Найти",
      from: "от",
      perYear: "/год",
      available: "Доступно",
      comingSoon: "Скоро",
      popular: "Популярно",
    },
    footer: {
      tagline: "Элитный хостинг с безопасностью, сертифицированной Google. Выделенная инфраструктура для разработчиков и компаний.",
      rights: "Все права защищены.",
      hosting: "Хостинг",
      company: "Компания",
      support: "Поддержка",
      about: "О нас",
      blog: "Блог",
      careers: "Карьера",
      contact: "Контакт",
      docs: "Документация",
      status: "Статус",
      privacy: "Конфиденциальность",
      terms: "Условия",
    },
    chat: {
      placeholder: "Задайте вопрос...",
      poweredBy: "Powered by LLaMA 3 · DevHosting ИИ",
      online: "Онлайн сейчас",
      suggestions: [
        "Какой план лучше для сайта?",
        "Принимаете Bitcoin?",
        "Как работает VPS?",
        "Цена домена .com?",
      ],
    },
  },
};

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: typeof translations["pt"];
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "pt",
  setLang: () => {},
  t: translations["pt"],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("pt");
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
